# Generated by Django 5.0.6 on 2024-06-21 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='../profile_default_o7qozg', upload_to='images/'),
        ),
    ]
