# Generated by Django 3.2.4 on 2024-07-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20240711_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(blank=True, default='../profile_default_o7qozg', upload_to='profile_pictures/'),
        ),
    ]
