# Generated by Django 5.0.6 on 2024-06-21 11:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Park',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, default='', upload_to='images/')),
                ('street', models.CharField(blank=True, max_length=255)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('postal_code', models.CharField(blank=True, max_length=20)),
                ('country', models.CharField(blank=True, max_length=100)),
                ('opening_hours', models.TextField(blank=True, max_length=255)),
                ('entrance_fees', models.TextField(blank=True, max_length=255)),
                ('total_number_of_rides', models.IntegerField(blank=True, null=True)),
                ('total_number_of_roller_coasters', models.IntegerField(blank=True, null=True)),
                ('total_number_of_shows', models.IntegerField(blank=True, null=True)),
                ('total_number_of_children_rides', models.IntegerField(blank=True, null=True)),
                ('park_size', models.FloatField(blank=True, null=True)),
                ('family_friendliness', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('thrill_factor', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('overall_rating', models.DecimalField(blank=True, decimal_places=2, max_digits=3, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
