# Generated by Django 5.0.6 on 2024-06-21 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='author',
            new_name='user',
        ),
    ]
