# Generated by Django 3.2.4 on 2024-07-08 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_rename_author_park_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='park',
            old_name='total_number_of_children_rides',
            new_name='total_number_of_coasters',
        ),
        migrations.RemoveField(
            model_name='park',
            name='city',
        ),
        migrations.RemoveField(
            model_name='park',
            name='country',
        ),
        migrations.RemoveField(
            model_name='park',
            name='entrance_fees',
        ),
        migrations.RemoveField(
            model_name='park',
            name='family_friendliness',
        ),
        migrations.RemoveField(
            model_name='park',
            name='opening_hours',
        ),
        migrations.RemoveField(
            model_name='park',
            name='park_size',
        ),
        migrations.RemoveField(
            model_name='park',
            name='postal_code',
        ),
        migrations.RemoveField(
            model_name='park',
            name='street',
        ),
        migrations.RemoveField(
            model_name='park',
            name='total_number_of_roller_coasters',
        ),
        migrations.RemoveField(
            model_name='park',
            name='total_number_of_shows',
        ),
        migrations.AddField(
            model_name='park',
            name='website',
            field=models.URLField(blank=True),
        ),
    ]
