# Generated by Django 3.2.4 on 2024-07-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0003_auto_20240708_0801'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='overall_rating',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
        migrations.AlterField(
            model_name='park',
            name='thrill_factor',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3, null=True),
        ),
    ]
