# Generated by Django 3.2.4 on 2024-07-26 12:21

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0004_auto_20240711_0804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='park',
            name='image',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='', force_format='WEBP', keep_meta=True, quality=75, scale=None, size=[500, 500], upload_to='images/'),
        ),
    ]
