# Generated by Django 5.0.6 on 2024-06-22 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='owner',
            new_name='user',
        ),
    ]
