# Generated by Django 5.0.6 on 2024-06-22 07:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0002_rename_owner_rating_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rating',
            old_name='text',
            new_name='explanation',
        ),
    ]
