# Generated by Django 5.0.6 on 2024-06-22 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0003_rename_text_rating_explanation'),
    ]

    operations = [
        migrations.AddField(
            model_name='rating',
            name='last_visisted_at',
            field=models.DateField(blank=True, null=True),
        ),
    ]
