# Generated by Django 5.0.6 on 2024-06-22 13:03

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks', '0002_rename_author_park_user'),
        ('ratings', '0005_alter_rating_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together={('user', 'park')},
        ),
    ]
