# Generated by Django 5.0.6 on 2024-06-22 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0006_alter_rating_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='rating',
            unique_together=set(),
        ),
    ]
