# Generated by Django 5.0.6 on 2024-06-22 16:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0008_rating_unique_user_park'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='rating',
            name='unique_user_park',
        ),
    ]
