# Generated by Django 3.2.4 on 2024-07-17 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0014_alter_rating_rating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='rating',
            name='last_visisted_at',
        ),
    ]
