# Generated by Django 3.2.4 on 2024-07-06 10:09

import contact.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform_edit_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='edit_token',
            field=models.UUIDField(default=contact.models.generate_unique_token, editable=False, unique=True),
        ),
    ]
