# Generated by Django 3.2.4 on 2024-07-06 17:55

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    ContactForm = apps.get_model('contact', 'ContactForm')
    for row in ContactForm.objects.all():
        if not row.edit_token:
            row.edit_token = uuid.uuid4()
            row.save(update_fields=['edit_token'])

class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactform_edit_token'),
    ]

    operations = [
        migrations.RunPython(gen_uuid),
    ]