# Generated by Django 3.2.4 on 2024-07-06 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_auto_20240706_1515'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactform',
            old_name='token',
            new_name='edit_token',
        ),
    ]
