# Generated by Django 3.2.4 on 2024-07-16 06:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0004_remove_contactform_edit_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactform',
            name='edit_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
        migrations.AddField(
            model_name='contactform',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
