# Generated by Django 3.2.4 on 2024-07-06 15:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_rename_token_contactform_edit_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactform',
            name='edit_token',
            field=models.UUIDField(default=uuid.uuid1, editable=False, unique=True),
        ),
    ]
